maze.cpp: maze::generator::PrimsGenerator Class Reference
maze::generator::PrimsGenerator Class Reference final
#include <generator.hpp>
Public Member Functions
void generate (Maze &maze) override
void clear () override
Detailed Description
Randomized Prim's algorithm.
See also
https://en.wikipedia.org/wiki/Maze_generation_algorithm#Randomized_Prim's_algorithm
Member Function Documentation
clear()
void maze::generator::PrimsGenerator::clear () inline override virtual
Clears data was used to generate a maze.
Must be called before regeneration of the maze. The function relies on constructor.
See also
https://stackoverflow.com/a/709161/11829849
maze::generator::Generator empty;
std::swap(*this, empty);
Implements maze::generator::Generator.
generate()
void maze::generator::PrimsGenerator::generate (Maze & maze) override virtual
Generates maze.
Parameters
maze All wall flags must be set.
Implements maze::generator::Generator.
References maze::details::ClearCellFlags(), maze::details::IsWallBetween(), maze::details::Neighbors(), and maze::details::RemoveWallBetween().
The documentation for this class was generated from the following files:
generator.hpp
generator.cpp