maze.cpp: maze::details Namespace Reference
maze::details Namespace Reference
Implementation details.
Classes
struct Cell
struct Coord
Functions
bool IsWallBetween (maze::Maze::CellPtr a, maze::Maze::CellPtr b)
Returns True, if there is a wall between a and b.
void RemoveWallBetween (maze::Maze::CellPtr a, maze::Maze::CellPtr b)
Removes wall between cells a and b.
double Distance (Maze::CellPtr a, Maze::CellPtr b)
Calculates euclidean distance between cells a and b assuming that the length from one cell to it's neighbors is 1.
void ClearCellFlags (Maze &maze, bool visited=true, bool inSolutionPath=false, bool backtracking=false, bool setWalls=false)
Maze::CellPtr PaintSolutionPath (Maze &maze, const std::unordered_map< Maze::CellPtr, Maze::CellPtr > &parent, Maze::CellPtr currPaint)
For each cell in the path (from maze.source() to maze.destination()), sets flag inTheSolutionPath to true.
std::vector< maze::Maze::CellPtr > Neighbors (maze::Maze::CellPtr c, Maze &maze)
Returns all possible neighbors of cell c. At most 4.
std::vector< maze::Maze::CellPtr > UnvisitedNeighbors (maze::Maze::CellPtr c, Maze &maze)
Returns unvisited neighbors of cell c.
std::vector< maze::Maze::CellPtr > AccessibleUnvisitedNeighbors (maze::Maze::CellPtr c, Maze &maze)
Returns unvisited neighbors of cell c such that there is no wall between a particular neighbor and the cell.
size_t GetRandomInteger (size_t a, size_t b)
Generates random integer ∈ [a; b].
template<typename T >
T RandomChoice (std::vector< T > &A)
template<typename C , typename T >
T RandomChoiceAndErase (C &A)
Detailed Description
Implementation details.
Class Documentation
maze::details::Coord
struct maze::details::Coord
Class Members
int x
int y
Function Documentation
ClearCellFlags()
void maze::details::ClearCellFlags (maze::Maze & maze, bool visited = true, bool inSolutionPath = false, bool backtracking = false, bool setWalls = false)
Clears specified Cell flags.
See also
Cell::visited
Cell::inSolutionPath
Cell::backtracking
Cell::left
Cell::right
Cell::bottom
Cell::top
Referenced by maze::generator::BacktrackerGenerator::generate(), maze::generator::KruskalsGenerator::generate(), and maze::generator::PrimsGenerator::generate().
Distance()
double maze::details::Distance (Maze::CellPtr a, Maze::CellPtr b)
Calculates euclidean distance between cells a and b assuming that the length from one cell to it's neighbors is 1.
d(a, b) = √((a.x - b.x)^2 + (a.y - b.y)^2)
Referenced by maze::solver::AStarSolver::solve().
RandomChoice()
template<typename T > T maze::details::RandomChoice (std::vector< T > & A)
Chooses a random value from A and returns it.
Parameters
A is a vector, because this function uses random access to be O(1). ()
Returns
random item ∈ A[0..n-1].
References GetRandomInteger().
Referenced by maze::generator::BacktrackerGenerator::generate().
RandomChoiceAndErase()
template<typename C , typename T > T maze::details::RandomChoiceAndErase (C & A)
Chooses a random value from A, erases it from the container and returns.
Parameters
A can be any container that supports iterating. ()
Returns
random item ∈ A[0..n-1].
References GetRandomInteger().